In [1]:
# Importing the dependencies

In [2]:
import numpy as np
import pandas as pd

In [3]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

In [4]:
# loading the diabetes dataset to a pandas DataFrame

In [5]:
diabetes_dataset = pd.read_csv("diabetes.csv")

In [6]:
diabetes_dataset.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [7]:
# number of rows and columns in the dataset

In [8]:
diabetes_dataset.shape

(768, 9)

In [9]:
#getting the statistical measures of the data

In [10]:
diabetes_dataset.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [11]:
diabetes_dataset['Outcome'].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [12]:
# 0--> Non-Diabetic , 1 --> Diabetic

In [13]:
diabetes_dataset.groupby('Outcome').mean()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
Outcome,,,,,,,,
0,3.298000,109.980000,68.184000,19.664000,68.792000,30.304200,0.429734,31.190000
1,4.865672,141.257463,70.824627,22.164179,100.335821,35.142537,0.550500,37.067164

In [14]:
# separating the features and labels

In [15]:
x = diabetes_dataset.drop(columns = 'Outcome', axis = 1)  #features

In [16]:
y = diabetes_dataset['Outcome']           #labels

In [17]:
print(x)

     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6
1              1       85             66             29        0  26.6
2              8      183             64              0        0  23.3
3              1       89             66             23       94  28.1
4              0      137             40             35      168  43.1
..           ...      ...            ...            ...      ...   ...
763           10      101             76             48      180  32.9
764            2      122             70             27        0  36.8
765            5      121             72             23      112  26.2
766            1      126             60              0        0  30.1
767            1       93             70             31        0  30.4

     DiabetesPedigreeFunction  Age
0                       0.627   50
1                       0.351   31
2                       0.672   32
3                       0.167   21
4                       2.288   33
..                        ...  ...
763                     0.171   63
764                     0.340   27
765                     0.245   30
766                     0.349   47
767                     0.315   23

[768 rows x 8 columns]

In [18]:
print(y)

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [19]:
# Data Standardization

In [20]:
scaler = StandardScaler()

In [21]:
standardized_data = scaler.fit_transform(x)

In [22]:
print(standardized_data)

[[ 0.63994726  0.84832379  0.14964075 ...  0.20401277  0.46849198
   1.4259954 ]
 [-0.84488505 -1.12339636 -0.16054575 ... -0.68442195 -0.36506078
  -0.19067191]
 [ 1.23388019  1.94372388 -0.26394125 ... -1.10325546  0.60439732
  -0.10558415]
 ...
 [ 0.3429808   0.00330087  0.14964075 ... -0.73518964 -0.68519336
  -0.27575966]
 [-0.84488505  0.1597866  -0.47073225 ... -0.24020459 -0.37110101
   1.17073215]
 [-0.84488505 -0.8730192   0.04624525 ... -0.20212881 -0.47378505
  -0.87137393]]

In [23]:
x = standardized_data
y = diabetes_dataset['Outcome']

In [24]:
print(x)
print(y)

[[ 0.63994726  0.84832379  0.14964075 ...  0.20401277  0.46849198
   1.4259954 ]
 [-0.84488505 -1.12339636 -0.16054575 ... -0.68442195 -0.36506078
  -0.19067191]
 [ 1.23388019  1.94372388 -0.26394125 ... -1.10325546  0.60439732
  -0.10558415]
 ...
 [ 0.3429808   0.00330087  0.14964075 ... -0.73518964 -0.68519336
  -0.27575966]
 [-0.84488505  0.1597866  -0.47073225 ... -0.24020459 -0.37110101
   1.17073215]
 [-0.84488505 -0.8730192   0.04624525 ... -0.20212881 -0.47378505
  -0.87137393]]
0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [25]:
# Train - Test Split

In [26]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, stratify=y, random_state=2)

In [27]:
print(x.shape, x_train.shape, x_test.shape)

(768, 8) (614, 8) (154, 8)

In [28]:
# Training the data

In [29]:
classifier = svm.SVC(kernel='linear')

In [30]:
#training the support vector machine classifier
classifier.fit(x_train, y_train)

SVC(kernel='linear')

In [31]:
# Accuracy Score on the Training data

In [32]:
x_train_prediction = classifier.predict(x_train)
training_data_accuracy = accuracy_score(x_train_prediction, y_train)
print('Accuracy score of the training data: ',training_data_accuracy)

Accuracy score of the training data:  0.7866449511400652

In [33]:
# Accuracy Score on the Testing data

In [34]:
x_test_prediction = classifier.predict(x_test)
testing_data_accuracy = accuracy_score(x_test_prediction, y_test)
print('Accuracy score of the testing data: ',testing_data_accuracy)

Accuracy score of the testing data:  0.7727272727272727

In [35]:
# Making the Predictive System

In [36]:
input_data = (10,168,74,0,0,38,0.537,34)

# changing the input data to numpy array
input_data_as_numpy_array = np.asarray(input_data)
print("Numpy Array: ",input_data_as_numpy_array)

# reshape the function as we are predicting for one instance
input_data_reshaped = input_data_as_numpy_array.reshape(1, -1)
print("Reshaped Numpy Array: ",input_data_reshaped )

# standardize the input data
# std_data = scaler.transform(input_data_reshaped)
# print("Standardized Numpy Array: ",std_data)

# Predicting whether particular person is diabetic or not
prediction = classifier.predict(input_data_reshaped)
print(prediction)

if(prediction[0]==0):
    print("The person is not Diabetic")
else:
    print("The person is Diabetic")

Numpy Array:  [ 10.    168.     74.      0.      0.     38.      0.537  34.   ]
Reshaped Numpy Array:  [[ 10.    168.     74.      0.      0.     38.      0.537  34.   ]]
[1]
The person is Diabetic

In [37]:
# # Saving the trained model
# import pickle
# filename = 'trained_model.save'
# pickle.dump(classifier, open(filename, 'wb'))

# # Loading the saved model
# loaded_model = pickle.load(open('trained_model.save','rb'))

In [38]:
# import pickle
# with open('model.pkl','wb') as file:
#     pickle.dump(classifier, file)